"""added column for expiry subscription email tracking

Revision ID: 1dcd047dff86
Revises: 724bc87e9cfc
Create Date: 2026-07-07 19:18:11.590694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcd047dff86'
down_revision: Union[str, Sequence[str], None] = '724bc87e9cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('expired_email_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'expired_email_sent_at')
    # ### end Alembic commands ###
