"""add user astrology table

Revision ID: 4e2ab26aa868
Revises: 498dcd2aa068
Create Date: 2026-04-18 18:57:59.219597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2ab26aa868'
down_revision: Union[str, Sequence[str], None] = '498dcd2aa068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_astrology_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('charts', sa.JSON(), nullable=False),
    sa.Column('dasha', sa.JSON(), nullable=False),
    sa.Column('yoga', sa.JSON(), nullable=False),
    sa.Column('dosha', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_astrology_data')
    # ### end Alembic commands ###
