"""added cloumn for free chat use

Revision ID: 4ec13604d80d
Revises: c7383b41e4a7
Create Date: 2026-07-05 17:35:12.879495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec13604d80d'
down_revision: Union[str, Sequence[str], None] = 'c7383b41e4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('free_chat_used', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_chat_used')
    # ### end Alembic commands ###
