"""added column for invoice and reminder

Revision ID: 724bc87e9cfc
Revises: 4ec13604d80d
Create Date: 2026-07-05 18:05:12.399905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724bc87e9cfc'
down_revision: Union[str, Sequence[str], None] = '4ec13604d80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('payment_transactions', sa.Column('invoice_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_subscriptions', sa.Column('expiry_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscriptions', 'expiry_reminder_sent_at')
    op.drop_column('payment_transactions', 'invoice_sent_at')
    op.drop_column('payment_transactions', 'invoice_number')
    # ### end Alembic commands ###
