"""removed unrequired column from session table

Revision ID: e4c6c643e4cf
Revises: af2230a58c63
Create Date: 2026-04-21 21:55:24.318126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4c6c643e4cf'
down_revision: Union[str, Sequence[str], None] = 'af2230a58c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_sessions', 'device_info')
    op.drop_column('refresh_sessions', 'user_agent')
    op.drop_column('refresh_sessions', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_sessions', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('refresh_sessions', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('refresh_sessions', sa.Column('device_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
