"""updated status to payment_status and stripe columns

Revision ID: fbbde8450b86
Revises: 1dcd047dff86
Create Date: 2026-07-11 09:00:06.448418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbde8450b86'
down_revision: Union[str, Sequence[str], None] = '1dcd047dff86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('payment_transactions', sa.Column('payment_status', sa.String(), nullable=False))
    op.add_column('payment_transactions', sa.Column('stripe_checkout_session_id', sa.String(), nullable=True))
    op.add_column('payment_transactions', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.alter_column('payment_transactions', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_payment_transactions_stripe_checkout_session_id'), 'payment_transactions', ['stripe_checkout_session_id'], unique=True)
    op.drop_column('payment_transactions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_transactions', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payment_transactions_stripe_checkout_session_id'), table_name='payment_transactions')
    op.alter_column('payment_transactions', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payment_transactions', 'stripe_payment_intent_id')
    op.drop_column('payment_transactions', 'stripe_checkout_session_id')
    op.drop_column('payment_transactions', 'payment_status')
    op.drop_column('payment_transactions', 'currency')
    # ### end Alembic commands ###
